-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 15:14:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Candys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Candys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Candys` DEFAULT CHARACTER SET utf8 ;
USE `Candys` ;

-- -----------------------------------------------------
-- Table `Candys`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`sale` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `procent` DOUBLE NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Candys`.`holiday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`holiday` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NULL,
  `discription` VARCHAR(1000) NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `id_sale` INT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_holiday2sale_idx` (`id_sale` ASC) VISIBLE,
  CONSTRAINT `fk_holiday2sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `Candys`.`sale` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Candys`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`grade` (
  `_id` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Candys`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`basket` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `numOfProd` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Candys`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`product` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `id_holiday` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_grade` INT NOT NULL,
  `price` DOUBLE NULL,
  `image` VARCHAR(900) NULL,
  `description` VARCHAR(1000) NULL,
  `id_basket` INT NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_prod2holiday_idx` (`id_holiday` ASC) VISIBLE,
  INDEX `fk_prod2grade_idx` (`id_grade` ASC) VISIBLE,
  INDEX `fk_prod2basket_idx` (`id_basket` ASC) VISIBLE,
  CONSTRAINT `fk_prod2holiday`
    FOREIGN KEY (`id_holiday`)
    REFERENCES `Candys`.`holiday` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prod2grade`
    FOREIGN KEY (`id_grade`)
    REFERENCES `Candys`.`grade` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prod2basket`
    FOREIGN KEY (`id_basket`)
    REFERENCES `Candys`.`basket` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Candys`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Candys`.`order` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `patronymic` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `obtain` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `id_basket` INT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_order2basket_idx` (`id_basket` ASC) VISIBLE,
  CONSTRAINT `fk_order2basket`
    FOREIGN KEY (`id_basket`)
    REFERENCES `Candys`.`basket` (`_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
